[options.entry_points]
console_scripts =
    orchestrator_node = agimus_demo_10_tiago_pro_bar_manip.orchestrator_server:main
    tf_base_publisher = agimus_demo_10_tiago_pro_bar_manip.base_tf_odom:main
    joint_test = agimus_demo_10_tiago_pro_bar_manip.debug_scripts.joint_test:main
    mpc_input_viz = agimus_demo_10_tiago_pro_bar_manip.debug_scripts.mpc_input_visualizer:main
    ee_pose_pub = agimus_demo_10_tiago_pro_bar_manip.debug_scripts.ee_input_state:main
    nav_controller_node = agimus_demo_10_tiago_pro_bar_manip.nav:main
    mocap_repositioning_node = agimus_demo_10_tiago_pro_bar_manip.reposition_origin_mocap:main
