---
qualisys_ip: 192.168.75.4
publishing_freq: 300      # Hz, must be in [1, 300]
ref_frame: world_mocap

bodies:
- name: reinforcement_bar
  tf_frame_name: bar_base_link
    # publish_odometry defaults to false
- name: tiago_base
  tf_frame_name: base_link_mocap

- name: table
  tf_frame_name: table_mocap
