plate:
  name: "pannel"
  height: 0.03
  length: 1.0
  width: 1.0
  border_height: 0.02
  border_thickness: 0.02
  # Utilisez des crochets pour faire une liste [x, y, z]
  glue_surface:
    length: 0.98
    width: 0.98
    height: 0.03
    stride: 0.05
    xyz: [0., 0., 0.03]
    rpy: [0., 0., 0.] # TODO mettre une rotation si besoin